# Generated by Django 5.0.6 on 2024-06-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='ФИО')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(null=True, upload_to='article')),
            ],
        ),
    ]
