# Generated by Django 5.0.6 on 2024-06-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('date', models.DateField(verbose_name='Дата добавления')),
            ],
        ),
    ]
