# Generated by Django 5.0.6 on 2024-06-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmo', '0005_report_time_vacancion_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('experience', models.IntegerField(verbose_name='Опыт работы (лет)')),
                ('photo', models.ImageField(blank=True, upload_to='doctors_photos/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
    ]
