# Generated by Django 5.0.6 on 2024-06-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmo', '0006_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
    ]
