# Generated by Django 5.0.6 on 2024-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmo', '0007_alter_doctor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='surname',
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_name',
            field=models.TextField(default=0, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(null=True, upload_to='article'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.TextField(default=0, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.TextField(verbose_name='Специализация'),
        ),
    ]
